---
title: "20200923 class"
author: "jacky wang"
date: "2020/10/1"
output: html_document
---

```{r setup, include=FALSE}

library(knitr)

opts_chunk$set(echo = TRUE, message = F, warning = T, eval=T)

# windows檔名不要有"-"號

```

```{r package, include=FALSE}

library(readr)
library(dplyr)

```





# CH2 Data Cleaning



# data frame

data frame為方形資料（list中的一種特殊資料形式），比list多了一種資料取法（矩陣取法）

```{r}

df1 <- data.frame(
  y=c(1, 3, 5), 
  x=c(0, -1, 1)
)

df2 <- list(
  y=c(1, 3, 5), 
  x=c(0, -1, 1)
)

df1[1, 2]
# df2[1, 2]    # 無法使用

df1[c(1, 2), c(1, 2)]
df1[c(1, 2), "x"]

```

```{r}

typeof(df1); typeof(df2)    # type相同
class(df1); class(df2)    # class不同

```

class不同，可用的method不同
```{r}

methods(class = "data.frame")
methods(class = "list")
```

## Ubike data

瀏覽網頁
```{r}
browseURL("https://data.ntpc.gov.tw/datasets?keyword=%E6%96%B0%E5%8C%97%E5%B8%82%E5%85%AC%E5%85%B1%E8%87%AA%E8%A1%8C%E8%BB%8A%E7%A7%9F%E8%B3%83%E7%B3%BB%E7%B5%B1%28YouBike%29")    # 瀏覽網頁
```

網路爬蟲：
1.  JSON是網路上最常見的資料形態
```{r}

library(jsonlite)

json_url <- "https://data.ntpc.gov.tw/api/datasets/71CD1490-A2DF-4198-BEF1-318479775E8A/json"

fromJSON(json_url)
# 因為list內每筆資料格式相同，fromJSON()將之自動轉成data frame

list_Ubike_nTp <- fromJSON(
  json_url, 
  simplifyDataFrame = F
)

```

2.  有CSV檔，先選CSV
```{r}

csv_url <- "https://data.ntpc.gov.tw/api/datasets/71CD1490-A2DF-4198-BEF1-318479775E8A/csv"

df_Ubike_nTp<- read_csv(csv_url)    # a connection to a file 

```
*可按右上方Import Dataset引入資料，再把程式碼貼過來。

```{r}

str(df_Ubike_nTp)

```












