---
title: "plan_taiwanBusinessCycles"
drake_cache: ".godCache"
---

drake_cache: ".（隱藏）暫存區檔案夾名稱"



環境設定
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=F)
library(rmd2drake)    # by tpemartin
library(drake)    # 流程控管套件
```

## makecondition

引入所需套件
```{r makecondition}

library(readr)
library(dplyr)
library(ggplot2)
library(svglite)

```





以下必須符合
  '''{r labelName}
  targetName = {...}
  且 labelName = targetName ，才可以形成drake plan。

存檔 -> 按上方Addins -> Rmd-plan-make

## data

```{r downloaddata}
downloaddata = {
  taiwanStatistics <- readr::read_csv(
    "https://www.dropbox.com/s/n6fuvpo4cbz0oth/taiwanEconomicGrowth.csv?dl=1")
  taiwanStatistics
}
```

```{r dataReady}
dataReady = {
  downloaddata %>%
  rename(
    "year"="X1"
  ) %>%
  mutate(
    across(
      everything(),
      as.numeric
    )
  )
}

```



## graph

```{r gg_taiwanEconomicGrowth}
gg_taiwanEconomicGrowth = {
  dataReady %>%
    ggplot()+
    geom_line(
      aes(
        x=year, y=`economic growth rate(%)`
      )
    )
}
```

```{r gg_taiwanEconomicGrowth, drake=F}
gg_taiwanEconomicGrowth = {
  dataReady %>%
    ggplot()+
    geom_line(
      aes(
        x=year, y=`economic growth rate(%)`
      ), color="red"
    )
}
```
drake=F：將此chunk排除在流程之外

```{r}
gg_taiwanEconomicGrowth
```

## export

```{r save_gg_taiwanEconomicGrowth}
save_gg_taiwanEconomicGrowth = {
  ggsave(
    "taiwanEconomicsGrowth.svg",
    gg_taiwanEconomicGrowth,
    width=8,
    height=5
  )
  
}
```

mk_plan_20200923_class()：更新plan
vis_plan_20200923_class()：plan流程圖
